apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: falco
  namespace: argocd
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: falco
  revisionHistoryLimit: 1
  source:
    helm:
      releaseName: falco
      parameters:
      - name: driver.kind
        value: ebpf
      - name: falcosidekick.enabled
        value: "true"
      - name: falcosidekick.webui.enabled
        value: "true"
    path: falco/resources
    repoURL: https://github.com/xinity/argo-falco.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
